name: "Soundgates"
description: "Interactive Music Synthesis on FPGAs"

highlighter: rouge
markdown: kramdown #specifies Markdown renderer

#redcarpet:
#  extensions: ["fenced_code_blocks", "tables", "with_toc_data"]

url: "http://epics.uni-paderborn.de/soundgates"
