######################################################################
##
## Filename: nco_tb.udo
## Created on: Tue Sep 10 15:14:27 Mitteleuropäische Sommerzeit 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
