
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.5 EDK_P.58f
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LEDS_8BIT_DEVICE_ID,
		XPAR_LEDS_8BIT_BASEADDR,
		XPAR_LEDS_8BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_8BIT_IS_DUAL
	},
	{
		XPAR_PUSH_BUTTONS_5BIT_DEVICE_ID,
		XPAR_PUSH_BUTTONS_5BIT_BASEADDR,
		XPAR_PUSH_BUTTONS_5BIT_INTERRUPT_PRESENT,
		XPAR_PUSH_BUTTONS_5BIT_IS_DUAL
	}
};


