######################################################################
##
## Filename: cordic.udo
## Created on: Sun Sep 08 11:27:46 Mitteleuropäische Sommerzeit 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
