######################################################################
##
## Filename: cordic_tb.udo
## Created on: Thu Sep 05 22:02:55 Mitteleuropäische Sommerzeit 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
